#!/usr/bin/env node

// Package DBHub as an MCP Bundle (.mcpb) for one-click installation in
// Claude Desktop and other MCPB-compatible clients.
//
// Layout of the staged bundle (dist-mcpb/bundle):
//   manifest.json   — mcpb/manifest.json with the version stamped from package.json
//   dbhub.toml      — read-only tool config; DSN interpolated from the DBHUB_DSN
//                     env var that the client sets from user settings (keychain)
//   icon.png        — extension icon
//   LICENSE
//   server/         — the tsup backend build (dist/), minus the HTTP-only
//                     workbench frontend, the --demo seed data (the bundle
//                     always connects via DBHUB_DSN), and type declarations
//   node_modules/   — runtime dependencies (tsup externalizes package.json
//                     `dependencies`) plus the database driver packages
//
// Run: pnpm run build:mcpb  (builds the backend first, then this script)

import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { join } from "node:path";
import { root, rootPkg, bundleVersion, mcpbFile, localBin } from "./mcpb-common.mjs";

const distDir = join(root, "dist");
const bundleDir = join(root, "dist-mcpb", "bundle");

// Every optional dependency is a bundled database driver, except the cloud
// auth packages: AWS IAM / Azure AD auth requires local cloud credential
// setup that does not fit the bundle's zero-setup, read-only use case, and
// they would triple the bundle size. Repackage with them added if needed.
const CLOUD_AUTH_PACKAGES = new Set(["@aws-sdk/rds-signer", "@azure/identity"]);
const drivers = Object.keys(rootPkg.optionalDependencies ?? {}).filter(
  (pkg) => !CLOUD_AUTH_PACKAGES.has(pkg)
);

function run(command, args, opts = {}) {
  const result = spawnSync(command, args, { stdio: "inherit", ...opts });
  if (result.error) {
    throw result.error;
  }
  if (result.status !== 0) {
    throw new Error(`${command} ${args.join(" ")} exited with status ${result.status}`);
  }
}

if (!existsSync(join(distDir, "index.js"))) {
  console.error("dist/index.js not found — run `pnpm run build:backend` first.");
  process.exit(1);
}

console.log(`Staging MCP Bundle for dbhub@${bundleVersion} ...`);
rmSync(join(root, "dist-mcpb"), { recursive: true, force: true });
mkdirSync(bundleDir, { recursive: true });

// 1. Server code, minus what the stdio bundle never uses
const excludedDirs = [join(distDir, "public"), join(distDir, "demo")];
cpSync(distDir, join(bundleDir, "server"), {
  recursive: true,
  filter: (src) =>
    !excludedDirs.some((dir) => src.startsWith(dir)) &&
    !src.endsWith(".d.ts") &&
    !src.endsWith(".DS_Store"),
});

// 2. Static bundle assets
cpSync(join(root, "mcpb", "dbhub.toml"), join(bundleDir, "dbhub.toml"));
cpSync(join(root, "mcpb", "icon.png"), join(bundleDir, "icon.png"));
cpSync(join(root, "LICENSE"), join(bundleDir, "LICENSE"));

// 3. Manifest with the version stamped from package.json
const manifest = JSON.parse(readFileSync(join(root, "mcpb", "manifest.json"), "utf-8"));
manifest.version = bundleVersion;
writeFileSync(join(bundleDir, "manifest.json"), JSON.stringify(manifest, null, 2) + "\n");

// 4. node_modules. npm (not pnpm) so the result is a plain, symlink-free tree
//    that survives zipping.
const dependencies = { ...rootPkg.dependencies };
for (const driver of drivers) {
  dependencies[driver] = rootPkg.optionalDependencies[driver];
}
writeFileSync(
  join(bundleDir, "package.json"),
  JSON.stringify(
    {
      name: "dbhub-mcpb",
      version: bundleVersion,
      private: true,
      type: "module",
      description: "Staged MCP Bundle contents for DBHub (generated by scripts/build-mcpb.mjs)",
      dependencies,
    },
    null,
    2
  ) + "\n"
);
console.log(`Installing runtime dependencies: ${Object.keys(dependencies).join(", ")} ...`);
run(
  "npm",
  ["install", "--omit=dev", "--no-audit", "--no-fund", "--no-package-lock", "--loglevel=error"],
  { cwd: bundleDir }
);

// 5. Validate the manifest and pack the bundle
const mcpb = localBin("mcpb");
if (!existsSync(mcpb)) {
  console.error("mcpb CLI not found — run `pnpm install` (it is a devDependency).");
  process.exit(1);
}
run(mcpb, ["validate", join(bundleDir, "manifest.json")]);
run(mcpb, ["pack", bundleDir, mcpbFile]);

const sizeMB = (statSync(mcpbFile).size / 1024 / 1024).toFixed(1);
console.log(`\nDone: ${mcpbFile} (${sizeMB} MB)`);
